<?php

use Drupal\node\NodeInterface;
use Drupal\taxonomy\TermInterface;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implement hook_page_attachments.
 *
 * @param array $attachments
 *   The attachments array.
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function recogito_integration_page_attachments(array &$attachments) {
  $routeName = \Drupal::routeMatch()->getRouteName();
  if (!in_array($routeName, ['entity.node.canonical', 'recogito_annotate_node'])) {
    return;
  }
  $config = \Drupal::config('recogito_integration.settings');
  $annotatables = $config->get('recogito_integration.annotatables') ?? [];
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!isset($annotatables[$node->getType()])) {
    return;
  }
  if (!$annotatables[$node->getType()]['enabled']) {
    return;
  }
  $currentUser = \Drupal::currentUser();
  $perms = [
    'view' => $currentUser->hasPermission('recogito view annotations'),
    'create' => $currentUser->hasPermission('recogito create annotations'),
    'edit' => $currentUser->hasPermission('recogito edit annotations'),
    'delete' => $currentUser->hasPermission('recogito delete annotations'),
    'edit-own' => $currentUser->hasPermission('recogito edit own annotations'),
    'delete-own' => $currentUser->hasPermission('recogito delete own annotations'),
  ];
  $attached = [
    'permissions' => $perms,
    'userData' => [
      'id' => \Drupal::request()->getHost() . '/user/' . $currentUser->id(),
      'displayName' => $currentUser->getDisplayName(),
    ],
    'admin' => $currentUser->isAuthenticated(),
  ];

  $attached['annotatable_fields'] = $annotatables[$node->getType()]['fields'];

  if ($config->get('recogito_integration.custom_annotations')) {
    $attached['custom_elements'] = explode('\n', $config->get('recogito_integration.custom_annotations_elements') ?? '');
  }
  else {
    $attached['custom_elements'] = [];
  }

  $vocab = $config->get('recogito_integration.vocabulary_name');
  $termList = [];
  if ($vocab) {
    $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree($vocab);
    $termList = array_map(function ($term) {
      return $term->name;
    }, $terms);
  }
  $attached['tagOptions'] = [
    'defaultTag' => $config->get('recogito_integration.default_tag') ?? [],
    'tagList' => $termList,
  ];

  $attachments['#attached']['drupalSettings']['recogito_integration'] = $attached;
  switch ($routeName) {
    case 'entity.node.canonical':
      $attachments['#attached']['library'][] = 'recogito_integration/recogito_user';
      break;

    case 'recogito_annotate_node':
      $attachments['#attached']['library'][] = 'recogito_integration/recogito_admin';
      break;
  }
}

/**
 * Implement hook_node_predelete.
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node entity.
 */
function recogito_integration_node_predelete(NodeInterface $node) {
  if (in_array($node->getType(), [
    'annotation_collection',
    'annotation',
    'annotation_textualbody',
  ])) {
    return;
  }
  $collections = getAnnotationCollection($node->id());
  foreach ($collections as $collection) {
    $annotation_references = $collection->get('field_annotation_reference')->getValue();
    foreach ($annotation_references as $reference) {
      $annotation = \Drupal::entityTypeManager()
        ->getStorage('node')
        ->load($reference['target_id']);
      if (isset($annotation)) {
        $textualBodies = $annotation->get('field_annotation_textualbodies')->getValue();
        deleteAnnotationTextualBody($textualBodies);
        $annotation->delete();
      }
    }
    $collection->delete();
  }
}

/**
 * Implement hook_taxonomy_term_predelete.
 *
 * @param \Drupal\taxonomy\TermInterface $term
 *   The term entity.
 */
function recogito_integration_taxonomy_term_predelete(TermInterface $term) {
  $vocabularyId = $term->bundle();
  $config = \Drupal::config('recogito_integration.settings');
  $selectedVocab = $config->get('recogito_integration.vocabulary_name') ?? '';
  if ($vocabularyId !== $selectedVocab) {
    return;
  }
  $textualBodies = getTagTextualBody($term->getName());
  foreach ($textualBodies as $textualBody) {
    $textualBody->delete();
  }
}

/**
 * Implement hook_form_alter.
 *
 * @param array $form
 *   The form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 * @param string $form_id
 *   The form ID.
 */
function recogito_integration_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (preg_match('/^node_.*_(edit|delete)_form$/', $form_id, $matches)) {
    $form_type = $matches[1];
    $nid = $form_state->getFormObject()->getEntity()->id();
    if (!$nid) {
      return;
    }
    $node = $form_state->getFormObject()->getEntity();
    if (in_array($node->getType(), [
      'annotation_collection',
      'annotation',
      'annotation_textualbody',
    ])) {
      return;
    }
    if (getAnnotationCollection($nid)) {
      switch ($form_type) {
        case 'edit':
          $msg = 'IMPORTANT INFORMATION:\n\n
          This page contains annotations. Updating this node may affect
          the positioning of existing annotations.\n\n Please double check
          the existing annotations after updating this page.';
          $form['actions']['submit'] = [
            '#type' => 'submit',
            '#value' => 'Save',
            '#attributes' => [
              'onclick' => 'if(!confirm("' . $msg . '")){return false;}',
            ],
            '#submit' => [
              '::submitForm',
              '::save',
              'menu_ui_form_node_form_submit',
            ],
            '#access' => TRUE,
            '#button_type' => 'primary',
            '#weight' => 5,
          ];
          break;

        case 'delete':
          $form['description']['#markup'] = '<strong><u>Warning:</u></strong><br>
          This page contains annotations. Deleting this page will also delete all 
          associated annotations.<br>
          <strong>This action cannot be undone!</strong>';
          break;
      }
    }
  }
  elseif (preg_match('/^taxonomy_term_(.*)_delete_form$/', $form_id, $matches)) {
    $config = \Drupal::config('recogito_integration.settings');
    $vocab = $config->get('recogito_integration.vocabulary_name') ?? '';
    if ($vocab && $matches[1] === $vocab) {
      $term = $form_state->getFormObject()->getEntity();
      if (getTagTextualBody($term->getName())) {
        $form['description']['#markup'] = '<strong><u>Warning:</u></strong><br>
        This term is used for tagging annotations. Deleting this term will
        remove the tag from annotations.<br>
        <strong>This action cannot be undone!</strong>';
      }
    }
  }
}

/**
 * Implement hook_preprocess_field.
 *
 * @param array $variables
 *   The variables array.
 */
function recogito_integration_preprocess_field(&$variables) {
  $config = \Drupal::config('recogito_integration.settings');
  $annotatables = $config->get('recogito_integration.annotatables') ?? [];
  $contentType = $variables['element']['#bundle'];
  if (!isset($annotatables[$contentType])) {
    return;
  }
  if (!$annotatables[$contentType]['enabled']) {
    return;
  }
  $fieldsAnnotate = $annotatables[$contentType]['fields'] ?? [];
  if (in_array($variables['element']['#field_name'], $fieldsAnnotate)) {
    $variables['attributes']['annotatable-field-id'] = $variables['element']['#field_name'];
  }
}

/**
 * Implement hook_preprocess_views_view_field.
 *
 * @param array $variables
 *   The variables array.
 */
function recogito_integration_preprocess_views_view_field(&$variables) {
  $field = $variables['field'];
  $config = \Drupal::config('recogito_integration.settings');
  $annotatables = $config->get('recogito_integration.annotatables') ?? [];
  $node = $variables['row']->_entity;
  if (!$node instanceof NodeInterface) {
    return;
  }
  $contentType = $node->getType();
  if (!isset($annotatables[$contentType])) {
    return;
  }
  if (!$annotatables[$contentType]['enabled']) {
    return;
  }
  $fieldsAnnotate = $annotatables[$contentType]['fields'] ?? [];
  if (in_array($field->field, $fieldsAnnotate)) {
    $variables['output'] = [
      '#prefix' => '<div annotatable-field-id="' . $field->field . '">',
      '#suffix' => '</div>',
      '#markup' => $variables['output'],
    ];
  }
}

/**
 * Query Annotation Collection based on URL.
 *
 * @param string $nodeId
 *   The node ID.
 */
function getAnnotationCollection($nodeId) {
  $field_storage = FieldStorageConfig::loadByName('node', 'field_annotation_collection_url');
  if (!$field_storage) {
    return [];
  }
  $url = '/node/' . $nodeId;
  return \Drupal::entityTypeManager()
    ->getListBuilder('node')
    ->getStorage()
    ->loadByProperties([
      'type' => 'annotation_collection',
      'field_annotation_collection_url' => $url,
      'status' => 1,
    ]);
}

/**
 * Query Textualbody Tags by Taxonomy Term.
 *
 * @param string $termName
 *   The term name.
 */
function getTagTextualBody($termName) {
  return \Drupal::entityTypeManager()
    ->getListBuilder('node')
    ->getStorage()
    ->loadByProperties([
      'type' => 'annotation_textualbody',
      'field_annotation_value' => $termName,
      'field_annotation_purpose' => 'tagging',
    ]);

}
