recogito_integration.settings:
  type: config_object
  label: 'Recogito Integration settings'
  mapping:
    recogito_integration:
      type: mapping
      mapping:
        annotation_vocab_name:
          type: text
          label: 'Annotation Vocabulary Name:'
