name: Automated testing

on: [push]

jobs:
  call-testing-workflow:
    uses: digitalutsc/reusable_workflows/.github/workflows/ci-testing.yml@main
    with:
      module_name: recogito_integration
      composer_name: drupal/recogito_integration
      test_suite: functional
